apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 429367298871.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googleclothes:208d20688c5bdca15c8285aedc8d2aad72677c2a
        ports:
        - containerPort: 80
