apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 429367298871.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googleclothes:a882fc69a729e7c80c4e70b3417ee1c48a1f2dc0
        ports:
        - containerPort: 80
