apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 429367298871.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googleclothes:cf5c59bfc10d450d73bc7bb77523bbea6063c010
        ports:
        - containerPort: 80
