apiVersion: v1
kind: Service
metadata:
  name: main-frontend-service
  labels:
    app: main-frontend
spec:
  type: LoadBalancer   # ðŸ‘ˆ makes it publicly accessible
  selector:
    app: main-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
