apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-computers:9a3e63d6c08210dd2487494fff956d405d371ae4
        ports:
        - containerPort: 80
