apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 429367298871.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlepay:208d20688c5bdca15c8285aedc8d2aad72677c2a
        ports:
        - containerPort: 80
