apiVersion: v1
kind: Service
metadata:
  name: payment-frontend-service
  labels:
    app: payment-frontend
spec:
  type: ClusterIP
  selector:
    app: payment-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
