apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 429367298871.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlegrocery:cf5c59bfc10d450d73bc7bb77523bbea6063c010
        ports:
        - containerPort: 80
